#include "Waterchip.h"
#include "Common/Keyboard/ScanCodeToText.h"

// TODO - separate test file per language
// TODO - different it() test for each key

describe("ScanCodeToText") begin
    test("English keyboard") begin

        variable shift = true;

        variable scancode;
        
        scancode = scan_code_to_text(1, "en");
        expect(scancode.text) to_equal("ESCAPE");
        expect(scancode.visible) to_be_false;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_false;

        scancode = scan_code_to_text(2, "en");
        expect(scancode.text) to_equal("1");
        expect(scancode.visible) to_be_true;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_false;
        //
        scancode = scan_code_to_text(2, "en", shift);
        expect(scancode.text) to_equal("!");
        expect(scancode.visible) to_be_true;
        expect(scancode.shift) to_be_true;
        expect(scancode.numpad) to_be_false;

        scancode = scan_code_to_text(14, "en");
        expect(scancode.text) to_equal("BACKSPACE");
        expect(scancode.visible) to_be_false;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_false;
        //
        scancode = scan_code_to_text(14, "en", shift);
        expect(scancode.text) to_equal("BACKSPACE");
        expect(scancode.visible) to_be_false;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_false;

        scancode = scan_code_to_text(55, "en");
        expect(scancode.text) to_equal("*");
        expect(scancode.visible) to_be_true;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_true;
        //
        scancode = scan_code_to_text(55, "en", shift);
        expect(scancode.text) to_equal("*");
        expect(scancode.visible) to_be_true;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_true;

        scancode = scan_code_to_text(156, "en");
        expect(scancode.text) to_equal("ENTER");
        expect(scancode.visible) to_be_false;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_true;
        //
        scancode = scan_code_to_text(156, "en", shift);
        expect(scancode.text) to_equal("ENTER");
        expect(scancode.visible) to_be_false;
        expect(scancode.shift) to_be_false;
        expect(scancode.numpad) to_be_true;

        // TODO - add all of them.
    end
end
